version: 2.1

orbs:
  python: circleci/python@1.5.0
  browser-tools: circleci/browser-tools@1.4.0

jobs:
  test-and-lint:
    docker:
      - image: cimg/python:3.9
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements-dev.txt
      - run:
          name: Lint with flake8
          command: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - run:
          name: Test formatting with black
          command: black . --check
      - run:
          name: Run tests
          command: pytest --headless

workflows:
  sample:
    jobs:
      - test-and-lint
