version: 2.1

orbs:
  python: circleci/python@1.5.0
  browser-tools: circleci/browser-tools@1.4.0

jobs:
  lint-and-test:
    docker:
      - image: cimg/python:3.9
    steps:
      - browser-tools/install-browser-tools
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements-dev.txt
      - run:
          name: Run tests
          command: pytest

workflows:
  sample:
    jobs:
      - lint-and-test
